apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marvel-ingress-v1
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
    ingress.kubernetes.io/disable-admission-webhook: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: marvel.assy.com
      http:
        paths:
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: deploy1-service
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marvel-ingress-v2-canary
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "20"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: marvel.assy.com
      http:
        paths:
          - path: /v2
            pathType: Prefix
            backend:
              service:
                name: deploy2-service
                port:
                  number: 80
